#! /usr/bin/env python
from waflib import Logs
import os

top = '.'

def options(opt):
	return

def configure(conf):
	if conf.options.SUPPORT_BSP2_FORMAT:
		conf.env.append_unique('DEFINES', 'SUPPORT_BSP2_FORMAT')

	conf.env.append_unique('DEFINES', 'TIER1')
	if conf.env.DEST_OS2 == 'android':
		conf.check_cc(lib='log')

def build(bld):
	libs = [ 'public', 'M' ]

	source = ['tier1.cpp', 'convar.cpp']

	includes = list()
	includes.append(str(bld.env.ENGINE))
	includes.append(str(bld.env.ENGINE) + "/server")
	includes.append(str(bld.env.ENGINE) + "/client")
	includes.append(str(bld.env.PUBLIC))
	includes.append(str(bld.env.COMMON))
	includes.append(str(bld.env.PMSHARED))
	includes.append(str(bld.env.ROOT))

	bld.stlib(
		source = source,
		target = 'tier1',
		features = 'c cxx',
		includes = includes,
		use = libs,
		defines = [],
		subsystem = bld.env.MSVC_SUBSYSTEM
	)