#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os
 
def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	defines = []
	source = bld.path.parent.ant_glob([
		'pm_shared/*.cpp',
	])
	source = []
	source += [
		'../../pm_shared/pm_debug.cpp',
		'../../pm_shared/pm_shared.cpp',
		'../../pm_shared/pm_math.cpp'
	]
	
	source += [
		'agrunt.cpp', 'airtank.cpp', 'aflock.cpp', 'animating.cpp', 'animation.cpp', 'apache.cpp', 
		'barnacle.cpp', 'barney.cpp', 'bigmomma.cpp', 'bloater.cpp', 'bmodels.cpp', 'bullsquid.cpp', 'buttons.cpp', 
		'cbase.cpp', 'client.cpp', 'combat.cpp', 'controller.cpp',
		'defaultai.cpp', 'doors.cpp', 
		'effects.cpp', 'explode.cpp',
		'flyingmonster.cpp', 'func_break.cpp', 'func_tank.cpp', 
		'game.cpp', 'gamerules.cpp', 'gargantua.cpp', 'genericmonster.cpp', 'ggrenade.cpp', 'globals.cpp', 'gman.cpp',
		'h_ai.cpp', 'h_battery.cpp', 'h_cine.cpp', 'h_cycler.cpp', 'h_export.cpp', 'hassassin.cpp', 'headcrab.cpp',
		'healthkit.cpp', 'hgrunt.cpp', 'hornet.cpp', 'houndeye.cpp',
		'ichthyosaur.cpp', 'islave.cpp', 'items.cpp', 
		'leech.cpp', 'lights.cpp', 
		'maprules.cpp', 'monstermaker.cpp', 'monsters.cpp', 'monsterstate.cpp', 'mortar.cpp', 'multiplay_gamerules.cpp',
		'nihilanth.cpp', 'nodes.cpp', 
		'observer.cpp', 'osprey.cpp', 
		'pathcorner.cpp', 'plane.cpp', 'plats.cpp', 'player.cpp', 'playermonster.cpp',
		'rat.cpp', 'roach.cpp',
		'schedule.cpp', 'scientist.cpp', 'scripted.cpp', 'singleplay_gamerules.cpp', 'skill.cpp',
		'sound.cpp', 'soundent.cpp', 'spectator.cpp', 'squadmonster.cpp', 'subs.cpp',
		'talkmonster.cpp', 'teamplay_gamerules.cpp', 'tempmonster.cpp', 'tentacle.cpp', 
		'triggers.cpp', 'turret.cpp',
		'util.cpp', 
		'weapons.cpp', 'world.cpp', 'xen.cpp', 'zombie.cpp',
		'../shared/hl1/weapon_crossbow.cpp',
		'../shared/hl1/weapon_crowbar.cpp',
		'../shared/hl1/weapon_egon.cpp',
		'../shared/hl1/weapon_gauss.cpp',
		'../shared/hl1/weapon_frag.cpp',
		'../shared/hl1/weapon_hornetgun.cpp',
		'../shared/hl1/weapon_mp5.cpp',
		'../shared/hl1/weapon_python.cpp',
		'../shared/hl1/weapon_rpg.cpp',
		'../shared/hl1/weapon_satchel.cpp',
		'../shared/hl1/weapon_shotgun.cpp',
		'../shared/hl1/weapon_squeakgrenade.cpp',
		'../shared/hl1/weapon_tripmine.cpp',
		'../shared/hl1/weapon_glock.cpp']
		
	if bld.env.VOICEMGR:
		source += bld.path.parent.ant_glob([
			'game_shared/voice_gamemgr.cpp',
		])
	else:
		defines += ['NO_VOICEGAMEMGR']
		
	#includes = Utils.to_list('. wpn_shared ../common ../engine ../pm_shared ../game_shared ../public')
	includes = list()
	includes.append(bld.env.ENGINE)
	includes.append(bld.env.COMMON)
	includes.append(bld.env.PMSHARED)
	includes.append(bld.env.SHARED)
	includes.append(bld.env.PUBLIC)
	includes.append(bld.env.ROOT)

	libs = ['public', 'mathlib']

	if bld.env.DEST_OS2 not in ['android']:
		install_path = os.path.join(str(bld.env.GAMEDIR), str(bld.env.SERVER_DIR))
	else:
		install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = 'server',
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = 2
	)
